########################################################################
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
########################################################################
AWSTemplateFormatVersion: 2010-09-09
Description:
  AWS Control Tower Execution IAM Role Creation. - 'common_prerequisites' solution in the repo,
  https://github.com/aws-samples/aws-security-reference-architecture-examples (cfct-1ssgnse2h)
Metadata:
  cfct:
    Version: 1.1
    Order: 2
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: General Properties
        Parameters:
          - cfctSolutionTagKey
          - cfctSolutionName
      - Label:
          default: Control Tower Role Attributes
        Parameters:
          - AWSControlTowerExecutionRoleName
    ParameterLabels:
      AWSControlTowerExecutionRoleName:
        default: AWS Control Tower Execution Role Name
      cfctSolutionName:
        default: cfct Solution Name
      cfctSolutionTagKey:
        default: cfct Solution Tag Key

Parameters:
  AWSControlTowerExecutionRoleName:
    AllowedValues: [AWSControlTowerExecution]
    Default: AWSControlTowerExecution
    Description: AWS Control Tower execution role name
    Type: String
  cfctSolutionName:
    AllowedValues: [cfct-common-prerequisites]
    Default: cfct-common-prerequisites
    Description: The cfct solution name. The default value is the folder name of the solution
    Type: String
  cfctSolutionTagKey:
    AllowedValues: [cfct-solution]
    Default: cfct-solution
    Description: The cfct solution tag key applied to all resources created by the solution that support tagging. The value is the cfctSolutionName.
    Type: String

Resources:
  AWSControlTowerRole:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: Specific role name provided for AWS Control Tower
          - id: W43
            reason: Administrator policy is required for the role
    Properties:
      RoleName: !Ref AWSControlTowerExecutionRoleName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS:
                - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AdministratorAccess
      Tags:
        - Key: !Ref cfctSolutionTagKey
          Value: !Ref cfctSolutionName

Outputs:
  oAWSControlTowerExecutionRoleArn:
    Description: AWS Control Tower Execution Role ARN
    Value: !GetAtt AWSControlTowerRole.Arn
  ocfctSolutionName:
    Description: cfct Solution Name
    Value: !Ref cfctSolutionName
